name: Deploy Honkit Site to GitHub Pages

on:
  push:
    branches:
      - main  # デプロイするブランチを指定

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Honkitで必要なNode.jsのバージョンを指定

      - name: Install dependencies
        run: npm install honkit  # Honkitと必要なパッケージをインストール
        run: npm install ./ # 依存関係をインストール

      - name: Build Honkit site
        run: npm run build  # Honkitのビルドコマンドを実行

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book  # Honkitの出力ディレクトリを指定
