name: Deploy Honkit to GitHub Pages

on:
  push:
    branches:
      - main  # デプロイするブランチ名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 適宜バージョンを変更してください

      - name: Install dependencies
        run: |
          npm install honkit  # honkit をインストール
          npm install undici@5.21.0 # undici をダウングレード
          npm install
          

      - name: Build Honkit
        run: npm run build # package.json の scripts に "build": "honkit build" を追加してください

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book  # Honkit の出力ディレクトリ